---
openapi: "3.0.1"
servers:
  - url: "http://localhost:8080"
    description: "Generated server url"
paths:
  /student:
    get:
      tags:
        - "student-controller"
      operationId: "getStudents"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Student"
    put:
      tags:
        - "student-controller"
      operationId: "updateStudent"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Student"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Student"
    post:
      tags:
        - "student-controller"
      operationId: "createStudent"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Student"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Student"
  /faculty:
    get:
      tags:
        - "faculty-controller"
      operationId: "getFaculties"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Faculty"
    put:
      tags:
        - "faculty-controller"
      operationId: "updateFaculty"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Faculty"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Faculty"
    post:
      tags:
        - "faculty-controller"
      operationId: "createFaculty"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Faculty"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Faculty"
  /student/{id}:
    get:
      tags:
        - "student-controller"
      operationId: "getStudentById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Student"
    delete:
      tags:
        - "student-controller"
      operationId: "deleteStudentById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Student"
  /student/age/{age}:
    get:
      tags:
        - "student-controller"
      operationId: "getStudentsByAge"
      parameters:
        - name: "age"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Student"
  /faculty/{id}:
    get:
      tags:
        - "faculty-controller"
      operationId: "getFacultyById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Faculty"
    delete:
      tags:
        - "faculty-controller"
      operationId: "deleteFacultyById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Faculty"
  /faculty/color/{color}:
    get:
      tags:
        - "faculty-controller"
      operationId: "getFacultiesByColor"
      parameters:
        - name: "color"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Faculty"
info:
components:
  schemas:
    Student:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        age:
          type: "integer"
          format: "int32"
    Faculty:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        color:
          type: "string"